### ISSUE TITLE
Module '"@nestjs/common"' has no exported member 'ModuleMetadata'

### ISSUE THREAD

**Issue by CLacaileSSG** [lehh/nestjs-soap#23]
Hi, 

I have an error when running my NestJS app that states that `Module '"@nestjs/common"' has no exported member 'ModuleMetadata'`.
I am running NestJS 7.0.0 (on Node 12) and nestjs-soap 2.2.1 (although I tried with nestjs-soap 2.0.0 and get the same error).

The console output is the following : 
```
node_modules/nestjs-soap/dist/soap-module-options.type.d.ts:2:10 - error TS2305: Module '"@nestjs/common"' has no exported member 'ModuleMetadata'.

2 import { ModuleMetadata, Type } from '@nestjs/common';
```

When I remove the `ModuleMetadata` import from the `soap-module-options.type.d.ts`, my IDE suggests me to import `ModuleMetadata` from `'@nestjs/common/interfaces'` which seems to fix the problem.

Note that it is not possible for me to upgrade to a newer version of NestJS.

Do you know what could be the problem please?

Many thanks in advance!

**Comment by CLacaileSSG** [comment]
Thanks for your response @lehh,

Here is a minimal package.json that should help you reproduce the bug (**do not forget that I am running Node 12**) :

```
{
  "name": "nest-typescript-starter",
  "private": true,
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/platform-express": "^7.0.0",
    "nestjs-soap": "^2.2.1",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.5.4"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.0.0",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.0.0",
    "@types/express": "^4.17.3",
    "@types/jest": "25.1.4",
    "@types/multer": "^1.4.7",
    "@types/node": "^13.9.1",
    "@types/passport-jwt": "^3.0.3",
    "@types/passport-local": "^1.0.33",
    "@types/supertest": "^2.0.8",
    "@types/yargs": "^15.0.13",
    "@typescript-eslint/eslint-plugin": "^2.23.0",
    "@typescript-eslint/parser": "^2.23.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-import": "^2.20.1",
    "jest": "^25.1.0",
    "jest-sonar": "^0.2.12",
    "prettier": "^1.19.1",
    "supertest": "^4.0.2",
    "ts-jest": "^26.4.3",
    "ts-loader": "^6.2.1",
    "ts-node": "^8.6.2",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```

**Comment by lehh** [comment]
I've tried to reproduce it with node v12.22.12, but I got an error with superagent instead of the nestjs-soap haha.
```bash
$ nest start
node_modules/@types/superagent/index.d.ts:23:10 - error TS2305: Module '"buffer"' has no exported member 'Blob'.

23 import { Blob } from "buffer";
            ~~~~

Found 1 error(s).
```
Anyways, one thing you can do is add this line to your tsconfig.json: `"skipLibCheck": true`. This will disable type checking for dependencies. I don't think this is the best way to solve it, but since you can't upgrade your dependencies and node version, this would be a workaround for now.
I'd also recommend deleting the .lock file, node_modules and dist folder too since this nestjs version you're using has the `ModuleMetadata` exported, so this error shouldn't be happening.

Nevertheless, the ModuleMetadata isn't being exported on some nestjs 7 and 6 versions and I found out a bug with async modules because of that. So thanks for bringing this issue up!

**Comment by CLacaileSSG** [comment]
Hi @lehh,

Many thanks, the `skipLibCheck` thing seems to do the trick! The superagent error is weird tho, I didn't get it in my environment.

Anyways, glad you could find a bug 😉
