### ISSUE TITLE
Error on creating the soap client

### ISSUE THREAD

**Issue by ferranmuntada** [lehh/nestjs-soap#28]
I've that issue :
![error issue](https://user-images.githubusercontent.com/11363936/195572872-1ec92cc3-80b0-4404-8189-e0bb4c249b7b.PNG)

can someone help me to solve this problem?
import Soap Module= 
![image](https://user-images.githubusercontent.com/11363936/195573115-52eb6c19-e4d9-49c8-b617-51d2ef6952af.png)

UseClass=
![image](https://user-images.githubusercontent.com/11363936/195574169-b0c0e171-bc27-4ac9-9a8e-c5de18d04753.png)

Thanks

**Comment by ferranmuntada** [comment]
This issue appears just starting with npm start.

thanks

**Comment by lehh** [comment]
Hi @ferranmuntada,

Firstly, which version of nestjs-soap are you using?

I did exactly the same using nestjs-soap latest version, with this SOAP service that I use for testing: `https://www.dataaccess.com/webservicesserver/NumberConversion.wso?wsdl`
And it worked fine.

Can you check if the environment variables are correct and the SOAP service you're trying to connect is working fine, please?

**Comment by ferranmuntada** [comment]
Hi lehh, i just found the error.
In local it works but when i upload to the server it fails.
It was cuz i was setting the header of the soap on the service constructor and the client was not already created..., but i can't understand why on local works and on the server just crash... :( 

thanks anyway I just changed where i set the header !

**Comment by ferranmuntada** [comment]
Hi @lehh  ,

I just worked on this , and I already saw that nestjs-soap 3.0.0 is not working with nestjs 9.0.0. 

Same error on reading create, I created a new project and It does not work.

Do you know anything? 

thanks!
