### ISSUE TITLE
Always getting the same error (v3)

### ISSUE THREAD

**Issue by eromerodev** [lehh/nestjs-soap#29]
In the browser or SoapUI have no problem to load the wsdl, but using this library always show the same error. (nestjs >= v8.4.0)

--
[Nest] 30912  - 10/28/2022, 5:27:01 PM   ERROR [SoapModule] Cannot read properties of undefined (reading 'create') 
 - An error occurred while creating the soap client. Check the SOAP service URL and status.
 

<img width="1071" alt="Screen Shot 2022-10-28 at 17 25 04" src="https://user-images.githubusercontent.com/87453638/198726784-5bc50aa4-b37b-449d-a850-724ca8d7c786.png">

**Comment by lehh** [comment]
Hi @eromerodev,

I can't reproduce this in my environment. Could you or @ferranmuntada please provide a repository that's having this error?
If you can't provide a repository, please share your package.json and the **exact** version(s) of nestjs you're using. The best would be a repository though.

Also, next time, it'd be great if you could copy paste your code, since I can't copy from an image 😅 .

Thanks.

**Comment by ialnezami** [comment]
Hey, 
I have same error
```
[Nest] 42352  - 03/11/2022 10:46:46     LOG [NestFactory] Starting Nest application...
[Nest] 42352  - 03/11/2022 10:46:46   ERROR [SoapModule] Cannot read properties of undefined (reading 'create') 
 - An error occurred while creating the soap client. Check the SOAP service URL and status.
[Nest] 42352  - 03/11/2022 10:46:46     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 42352  - 03/11/2022 10:46:46     LOG [InstanceLoader] SoapModule dependencies initialized +0ms
[Nest] 42352  - 03/11/2022 10:46:46     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 42352  - 03/11/2022 10:46:46     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 42352  - 03/11/2022 10:46:46     LOG [RoutesResolver] AppController {/}: +2ms
[Nest] 42352  - 03/11/2022 10:46:46     LOG [RouterExplorer] Mapped {/, GET} route +1ms
[Nest] 42352  - 03/11/2022 10:46:46     LOG [NestApplication] Nest application successfully started +1ms
```
i'm not sure how to repreduce this error, it's a new project i test the url with postman it's work and i get the reponse

**Comment by ialnezami** [comment]
Hey, 
i had to fix http.js file in `function HttpClient(options)` as below to get my code work , i do not know it it's the best way, but it's work...

```
var HttpClient = /** @class */ (function () {
    function HttpClient(options) {
        options = options || {};
        this.options = options;
        try {
        this._request = options.request || req;
       // this._request = options.request || req["default"].create();
            
        } catch (error) {
            console.log("🚀 ~ file: http.js ~ line 45 ~ */ ~ HttpClient ~ error", error)
            
        }
    }
```

**Comment by lehh** [comment]
Hi guys, I think I've found the problem, thanks to @ialnezami.

This is a problem in the [soap](https://www.npmjs.com/package/soap) package that is having incompatibilities with the newest axios 1.0.0 version.
What I suggest for now, for any of you that is having this problem, is to install axios v0.27.2 in your project.
Meanwhile, I will try to open a PR in the soap repository to fix that.
