### ISSUE TITLE
SoapModuleOptions needs to accept client options

### ISSUE THREAD

**Issue by bitsofinfo** [lehh/nestjs-soap#3]
SoapModuleOptions needs to accept client options

i.e. expose ability to pass options that make it here https://github.com/lehh/nestjs-soap/blob/b8fdabe0c61b83b005c31fb0ec735090bf08895c/src/soap-providers.ts#L10

**Comment by lehh** [comment]
Yes, this needs to be done. I will try to take a look at that this week.
Thanks!

**Comment by bitsofinfo** [comment]
any chance this can be added right now Im just manually creating the provider configs myself calling node soap manually

**Comment by lehh** [comment]
Just released the feature in #4.
I couldn't do it later, sorry.
